// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamManagementService.Data;

#nullable disable

namespace TeamManagementService.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20251204234310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamManagementService.Model.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            TeamName = "Blinders"
                        },
                        new
                        {
                            TeamId = 2,
                            TeamName = "Sockers"
                        },
                        new
                        {
                            TeamId = 3,
                            TeamName = "Lighters"
                        },
                        new
                        {
                            TeamId = 4,
                            TeamName = "Rainers"
                        },
                        new
                        {
                            TeamId = 5,
                            TeamName = "Timers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
