// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamManagementService.Data;

#nullable disable

namespace TeamManagementService.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20251205002554_AddCreatedAtToTeam")]
    partial class AddCreatedAtToTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamManagementService.Model.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 25, 54, 309, DateTimeKind.Utc).AddTicks(5657),
                            TeamName = "Blinders"
                        },
                        new
                        {
                            TeamId = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 25, 54, 309, DateTimeKind.Utc).AddTicks(5659),
                            TeamName = "Sockers"
                        },
                        new
                        {
                            TeamId = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 25, 54, 309, DateTimeKind.Utc).AddTicks(5660),
                            TeamName = "Lighters"
                        },
                        new
                        {
                            TeamId = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 25, 54, 309, DateTimeKind.Utc).AddTicks(5661),
                            TeamName = "Rainers"
                        },
                        new
                        {
                            TeamId = 5,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 25, 54, 309, DateTimeKind.Utc).AddTicks(5662),
                            TeamName = "Timers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
